name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: htslib
      run: |
        wget https://github.com/samtools/htslib/archive/1.10.2.tar.gz
        tar xf 1.10.2.tar.gz
        cd htslib-1.10.2
        autoheader
        autoconf
        ./configure
        make
        make install
    - name: autoconf
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: make install
